### ISSUE TITLE
Error in rule generate_consensus_sequences V1.2.1

### ISSUE THREAD

**Issue by jeroencremer** [polio-nanopore/piranha#242]
Dear Developers,

Installation command: mamba create -n piranha -c bioconda piranha-polio=1.2.1 -y
Installation command: mamba create -n piranha-V2.5 -c bioconda piranha-polio=1.2.1 -y
The installs of both versions seem to be going well.

It look like the same problem as "issue #236 " but now with the command line versions of Piranha.
We seem to have the same problem with both versions V1.2.1 and 1.2.5
This sample works with the piranhaGUI version 1.2.1

[errorV1.2.1.txt](https://github.com/user-attachments/files/16467957/errorV1.2.1.txt)
[errorV1.2.5.txt](https://github.com/user-attachments/files/16467958/errorV1.2.5.txt)

Thanks in advance for the help.

Jeroen Cremer

**Comment by rmcolq** [comment]
I've just merged in the PR which had fixes to the environment file and docker image. Hopefully that will soon solve your problem - not released yet as there are a few more unrelated changes in progress at the moment which will very shortly be done.

**Comment by jeroencremer** [comment]
Dear Developers,

Installation command: mamba create -n piranha -c bioconda piranha-polio=1.3 -y

It look like the same problem as "issue https://github.com/polio-nanopore/piranha/issues/236 " but now with the command line versions of Piranha.
The problem still seems to be present in version 1.3

Thanks in advance for the help.

[error.txt](https://github.com/user-attachments/files/16657038/error.txt)

**Comment by rmcolq** [comment]
To be clear - are you installing the environment file first? Or just installing piranha from bioconda?

**Comment by jeroencremer** [comment]
Installing piranha from bioconda.

**Comment by rmcolq** [comment]
What operating system are you using? Are you able to run in a Docker container instead of on the command line?

I'm not sure what the process is for generating the bioconda recipe, but I know that there is a problem with a version of medaka which pip installs several packages in such a way that is incompatible with some computer architectures (including mac M1 and some linux).

Could you resend that error, it's not loading

**Comment by jeroencremer** [comment]
We have an linux LSF-based computer cluster.
It's not possible to use the docker container on our netwerk.
On my private laptop, it runs fine

[Failed to build medaka pyspoa.txt](https://github.com/user-attachments/files/16661999/Failed.to.build.medaka.pyspoa.txt)

**Comment by rmcolq** [comment]
You could try mirroring the additional steps I took in the Dockerfile in your conda environment and see if they fix it for you too:
```
pip uninstall -y tensorflow keras pyabpoa
conda install -y -c conda-forge tensorflow~=2.11 keras~=2.11
```

**Comment by rmcolq** [comment]
That error also states that medaka failed to be installed because of ` RuntimeError: Unsupported compiler -- at least C++11 support is needed!`

**Comment by jeroencremer** [comment]
-->(mamba create -n piranha -c bioconda piranha-polio=1.3 -y)
Will it be possible to get the Mamba Pipline working?
to fix the issue with "Error in rule generate_consensus_sequences"
Or will it not be possible to make this work in the short term?

-->(git clone https://github.com/polio-nanopore/piranha.git)
I will try to solve the C++11 problem
to be able to install the pipeline in this way.

**Comment by aineniamh** [comment]
Going to close as the issue has gone stale- can reopen if it's still unresolved or anything changes!
